### ISSUE TITLE
Authorization: reset password

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-backend#12]
This is what I expect the reset password endpoint to function. But feel free to add any enhancements if needed. 

ResetPassword:
	- verify uuid token (if not expired or invalid)
		- if not valid send a 403 (Forbidden) status code with “invalid token” message
	- update password (hashed password)
	- send a 201 status code with “successful” message

**Comment by salomondush** [comment]
How do we know which user to reset the password for if they all have the same username?

**Comment by NickkTMD** [comment]
ChangePasswordEndpoint
- if the user has normal permissions they can only change their own password
- if its an admin, they are able to change anybody's password (pass in username and password)
