### ISSUE TITLE
Authorization: Generate new uuid token

### ISSUE THREAD

**Issue by salomondush** [ChangePlusPlusVandy/UFAR-backend#13]
GenerateNewUUID:
- req.body will have a string indicating the type of user (admin or normal) the token is created for.

	- first make sure that the current user is authorized and is admin
	     - if not authorized, send a 404 status code with a message "user doesn't have required privileges/not authorized"
	- then create a new UUIDToken instance with an expiration date within 2 hours, and `role` set to the type of user
	- send a response with a 200 status code including the newly created UUID.

**Comment by so-mimi** [comment]
試しにこれなおしてみてください
